name: watermark_anything
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10.14

  - pytorch==2.5.1
  - pytorch-cuda==12.4
  - torchvision==0.20.1

  - pywget==3.2

  - pip:
    - jupyter==1.1.1
    - streamlit==1.40.2
    - streamlit-drawable-canvas==0.9.3
    - streamlit-keyup==0.2.4
    - gradio[mcp]==5.28.0
    # gradio[mcp] 5.28.0 depends on pydantic>=2.11
    - pydantic==2.11.4
    - wrapt-timeout-decorator==1.5.1
    - -r ./watermark-anything/requirements.txt
    # for label-studio development and test
    - -r label/requirements_base.txt
    - -r label/requirements_dev.txt
    - -r label/requirements_test.txt
