name: watermark_anything
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10.14

  - pytorch==2.5.1
  - pytorch-cuda==12.4
  - torchvision==0.20.1

  - pywget==3.2

  - pip:
    - jupyter==1.1.1
    - -r ./watermark-anything/requirements.txt
