

services:
  labelstudio:
    image: heartexlabs/label-studio
    container_name: label-studio
    environment:
      - LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=true
      - LABEL_STUDIO_USERNAME=label@localhost
      - LABEL_STUDIO_PASSWORD=label.123
      - LABEL_STUDIO_USER_TOKEN=label-token
    ports:
      - "8080:8080"

  wam_label:
    image: xiaoyao9184/watermark-anything:main
    container_name: wam-label
    working_dir: /workspace/label
    command: label-studio-ml start --root-dir /workspace label
    environment:
      - LABEL_STUDIO_API_KEY=label-token
      - TORCH_DEVICE=cpu
    ports:
      - "9090:9090"
    volumes:
      - ./../../watermark-anything/checkpoints/checkpoint.pth:/app/checkpoints/checkpoint.pth
