
FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3-pip \
    libgl1-mesa-glx \
    libsm6 \
    libxext6 \
    libglib2.0-0 \
    libxrender-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip

RUN pip3 install --no-cache-dir \
    jupyter==1.1.1

COPY ./watermark-anything/requirements.txt /app/requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

COPY ./watermark-anything /app

RUN pip3 install --no-cache-dir \
    streamlit==1.40.2 \
    streamlit-drawable-canvas==0.9.3 \
    streamlit-keyup==0.2.4 \
    gradio==5.8.0

COPY ./streamlit /workspace/streamlit
COPY ./gradio /workspace/gradio

EXPOSE 8888
EXPOSE 8501
EXPOSE 7860

VOLUME /app/checkpoints

ENV APP_PATH=/app
ENV GRADIO_SERVER_NAME="0.0.0.0"

CMD ["jupyter", "notebook", "--allow-root", "--ip", "0.0.0.0"]
