
name: HuggingFace Space Sync

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  push-hf-space:
    name: Push source code to HuggingFace
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync to HuggingFace
        uses: xiaoyao9184/huggingface-sync-action@3d79db537a90f9b057ed1f4ab0ee7119b4c15259
        with:
          huggingface_repo_id: '${{ secrets.HF_USERNAME }}/watermark-anything'
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: 'space'
          private: false
          space_sdk: 'gradio'
          subdirectory: 'gradio'
          include_readme: true
          generate_message: true
